openapi: 3.0.0
info:
  title: 宅配型買取サービスAPI
  version: 0.0.1
servers:
  - url: http://localhost:3000/api
    description: 宅配型買取サービスAPIです。
tags:
  - name: Customer
paths:
  /customer:
    get:
      tags: [ "Customer" ]
      summary: 顧客情報取得
      description: 顧客情報を取得する。
      operationId: getCustomer
      parameters:
        - in: query
          name: tel
          schema:
            type: string
      responses:
        '200':
          description: 取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCustomerResponse'
    post:
      tags: [ "Customer" ]
      summary: 顧客情報登録
      description: 顧客情報を登録する。
      operationId: postCustomer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                tel:
                  type: string
      responses:
        default:
          description: 登録完了
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'

components:
  schemas:
    GetCustomerResponse:
      type: object
      description: 顧客情報取得APIのレスポンススキーマ
      properties:
        isSuccess:
          type: boolean
          description: 成功判定
          example: true
        message:
          type: string
          description: エラーメッセージ等（成功時は基本空文字列）
          example: ''
        body:
          $ref: "#/components/schemas/Customer"
    Customer:
      type: object
      description: 記事
      properties:
        id:
          type: integer
          format: int64
          description: 会員ID
          example: 1
        name:
          type: string
          description: 名前
          example: 山田太郎
        tel:
          type: string
          description: 電話番号
          example: 030-1111-2222