version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "3"

x-dev-base-environment:
  &dev-base-environment
  MYSQL_ROOT_PASSWORD: pass
  MYSQL_DATABASE: db
  MYSQL_USER: user
  MYSQL_PASSWORD: pass

volumes:
  mysql_data: { driver: local }

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: ./swagger/openapi-doc.yaml
    ports:
      - '9001:8080'

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "9002:8080"

  redoc:
    image: redocly/redoc
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      SPEC_URL: ./swagger/openapi-doc.yaml
      PORT: 8080
    ports:
      - '9003:8080'

  nest:
    build:
      context: .
      dockerfile: nest.Dockerfile
    volumes:
      - .:/app
    working_dir: /app/nest-app
    logging: *default-logging
    command: yarn start:dev
    environment:
      <<: *dev-base-environment
      FRONTEND_URI: 'http://localhost:8000'
    env_file:
      - ./nest-app/.env
    tty: true
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  echo:
    build:
      context: .
      dockerfile: echo.Dockerfile
    volumes:
      - .:/app
    working_dir: /app/echo-app
    depends_on:
      - mysql
    command: ["./start.sh"]
    environment: *dev-base-environment
    ports:
      - '3001:3001'

  react:
    build:
      context: .
      dockerfile: react.Dockerfile
    volumes:
      - .:/app
    working_dir: /app/react-app
    logging: *default-logging
    command: yarn start
    tty: true
    ports:
      - "8000:8000"