version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "3"
volumes:
  mysql_data: { driver: local }
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql

  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: ./swagger/openapi-doc.yaml
    ports:
      - '9001:8080'

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "9002:8080"

  redoc:
    image: redocly/redoc
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      SPEC_URL: ./swagger/openapi-doc.yaml
      PORT: 8080
    ports:
      - '9003:8080'

  nest:
    build:
      context: .
      dockerfile: nest.Dockerfile
    volumes:
      - .:/app
    working_dir: /app/nest
    logging: *default-logging
    command: yarn start:dev
    tty: true
    depends_on:
      - mysql
    ports:
      - "3000:3000"